#pragma once
namespace Sokoban
{
	enum Type
	{
		EMPTY,GROUND,WALL,BOX,TARGET,PLAYER, DIRECTION_BUTTON, SAVE_BUTTON, ZOOM_IN, ZOOM_OUT,LOAD_BUTTON, RELOAD_BUTTON, ROTATE_LEFT_BUTTON, ROTATE_RIGHT_BUTTON
	};
};